import {defineArrayMember, defineField, defineType} from 'sanity'

export const contactPage = defineType({
  name: 'contactPage',
  title: 'Pagina Contact',
  type: 'document',
  groups: [
    {name: 'seo', title: 'SEO'},
    {name: 'hero', title: 'Hero'},
    {name: 'topics', title: 'Contactonderwerpen'},
    {name: 'welcome', title: 'Welkom'},
    {name: 'direct', title: 'Direct contact'},
    {name: 'practical', title: 'Praktische informatie'},
    {name: 'faq', title: 'Veelgestelde vraag'},
  ],
  fields: [
    defineField({name: 'title', title: 'Interne titel', type: 'string', initialValue: 'Contact', validation: (rule) => rule.required().max(96)}),
    defineField({name: 'isTestData', title: 'Testdata', type: 'boolean', hidden: true, readOnly: true, initialValue: false}),
    defineField({name: 'seoTitle', title: 'SEO-titel', type: 'string', group: 'seo', validation: (rule) => rule.required().max(70)}),
    defineField({name: 'seoDescription', title: 'SEO-beschrijving', type: 'text', rows: 3, group: 'seo', validation: (rule) => rule.required().max(170)}),
    defineField({name: 'heroEyebrow', title: 'Bovenregel hero', type: 'string', group: 'hero', validation: (rule) => rule.required().max(80)}),
    defineField({name: 'heroTitle', title: 'Hero-titel', type: 'string', group: 'hero', validation: (rule) => rule.required().max(96)}),
    defineField({name: 'heroIntro', title: 'Hero-introductie', type: 'text', rows: 3, group: 'hero', validation: (rule) => rule.required().max(300)}),
    defineField({name: 'heroImage', title: 'Hero-afbeelding', type: 'image', group: 'hero', options: {hotspot: true}, validation: (rule) => rule.required()}),
    defineField({name: 'heroImageAlt', title: 'Alt-tekst hero', type: 'string', group: 'hero', validation: (rule) => rule.required().max(160)}),
    defineField({name: 'emailCtaLabel', title: 'Tekst e-mailknop', type: 'string', group: 'hero', validation: (rule) => rule.required().max(48)}),
    defineField({name: 'phoneCtaLabel', title: 'Tekst telefoonknop', type: 'string', group: 'hero', validation: (rule) => rule.required().max(48)}),
    defineField({
      name: 'contactTopics',
      title: 'Contactonderwerpen',
      type: 'array',
      group: 'topics',
      of: [defineArrayMember({
        name: 'contactTopic',
        title: 'Contactonderwerp',
        type: 'object',
        fields: [
          defineField({name: 'title', title: 'Titel', type: 'string', validation: (rule) => rule.required().max(80)}),
          defineField({name: 'text', title: 'Toelichting', type: 'text', rows: 3, validation: (rule) => rule.required().max(280)}),
          defineField({
            name: 'icon',
            title: 'Icoon',
            type: 'string',
            options: {
              list: [
                {title: 'Vraag', value: 'question'},
                {title: 'Boeking', value: 'calendar'},
                {title: 'Lid worden', value: 'people'},
                {title: 'Repetitie', value: 'music'},
              ],
              layout: 'radio',
            },
            validation: (rule) => rule.required(),
          }),
          defineField({name: 'linkLabel', title: 'Linktekst', type: 'string', validation: (rule) => rule.max(48)}),
          defineField({name: 'linkTarget', title: 'Linkdoel', type: 'url', validation: (rule) => rule.uri({scheme: ['http', 'https', 'mailto', 'tel'], allowRelative: true})}),
        ],
        preview: {select: {title: 'title', subtitle: 'text'}},
      })],
      validation: (rule) => rule.required().length(4),
    }),
    defineField({name: 'welcomeTitle', title: 'Welkomsttitel', type: 'string', group: 'welcome', validation: (rule) => rule.required().max(120)}),
    defineField({name: 'welcomeText', title: 'Welkomsttekst', type: 'text', rows: 4, group: 'welcome', validation: (rule) => rule.required().max(500)}),
    defineField({name: 'welcomeImage', title: 'Welkomstafbeelding', type: 'image', group: 'welcome', options: {hotspot: true}, validation: (rule) => rule.required()}),
    defineField({name: 'welcomeImageAlt', title: 'Alt-tekst welkomstafbeelding', type: 'string', group: 'welcome', validation: (rule) => rule.required().max(160)}),
    defineField({
      name: 'welcomePoints',
      title: 'Kernpunten',
      type: 'array',
      group: 'welcome',
      of: [defineArrayMember({type: 'string', validation: (rule) => rule.required().max(160)})],
      validation: (rule) => rule.required().min(1).max(6),
    }),
    defineField({name: 'directContactTitle', title: 'Titel direct contact', type: 'string', group: 'direct', validation: (rule) => rule.required().max(120)}),
    defineField({name: 'directContactText', title: 'Toelichting direct contact', type: 'text', rows: 3, group: 'direct', validation: (rule) => rule.required().max(360)}),
    defineField({name: 'emailAddress', title: 'E-mailadres', type: 'string', group: 'direct', validation: (rule) => rule.email().max(254)}),
    defineField({name: 'phoneNumber', title: 'Telefoonnummer', type: 'string', group: 'direct', description: 'Laat leeg wanneer nog geen openbaar telefoonnummer is vastgesteld.', validation: (rule) => rule.max(40)}),
    defineField({name: 'availabilityText', title: 'Bereikbaarheid', type: 'text', rows: 2, group: 'direct', validation: (rule) => rule.max(240)}),
    defineField({name: 'rehearsalInvitation', title: 'Uitnodiging repetitiebezoek', type: 'text', rows: 2, group: 'direct', validation: (rule) => rule.max(280)}),
    defineField({name: 'practicalTitle', title: 'Titel praktische informatie', type: 'string', group: 'practical', validation: (rule) => rule.required().max(120)}),
    defineField({name: 'rehearsalEvening', title: 'Repetitieavond', type: 'string', group: 'practical', validation: (rule) => rule.required().max(80)}),
    defineField({name: 'rehearsalTimes', title: 'Repetitietijden', type: 'string', group: 'practical', validation: (rule) => rule.max(120)}),
    defineField({name: 'rehearsalLocation', title: 'Repetitielocatie', type: 'string', group: 'practical', validation: (rule) => rule.max(160)}),
    defineField({name: 'address', title: 'Adres', type: 'string', group: 'practical', validation: (rule) => rule.max(200)}),
    defineField({name: 'agendaLinkLabel', title: 'Linktekst agenda', type: 'string', group: 'practical', validation: (rule) => rule.max(48)}),
    defineField({name: 'agendaLink', title: 'Link agenda', type: 'url', group: 'practical', validation: (rule) => rule.uri({scheme: ['http', 'https'], allowRelative: true})}),
    defineField({name: 'aboutLinkLabel', title: 'Linktekst Over Spontaan', type: 'string', group: 'practical', validation: (rule) => rule.max(48)}),
    defineField({name: 'aboutLink', title: 'Link Over Spontaan', type: 'url', group: 'practical', validation: (rule) => rule.uri({scheme: ['http', 'https'], allowRelative: true})}),
    defineField({name: 'faqTitle', title: 'Titel FAQ', type: 'string', group: 'faq', validation: (rule) => rule.required().max(120)}),
    defineField({name: 'faqQuestion', title: 'FAQ-vraag', type: 'string', group: 'faq', validation: (rule) => rule.required().max(180)}),
    defineField({name: 'faqAnswer', title: 'FAQ-antwoord', type: 'text', rows: 4, group: 'faq', validation: (rule) => rule.required().max(600)}),
    defineField({name: 'closingCtaText', title: 'Slot-CTA-tekst', type: 'text', rows: 2, group: 'faq', validation: (rule) => rule.max(280)}),
  ],
  preview: {select: {title: 'title', subtitle: 'heroIntro', media: 'heroImage'}},
})
