backend:
  name: github
  repo: JimGroen2160/spontaan-website
  branch: main

  base_url: https://plain-morning-bab6.jim-groen14.workers.dev
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: pagina
    label: "Pagina's"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Titel"
        name: "title"
        widget: "string"
      - label: "Datum"
        name: "date"
        widget: "datetime"
      - label: "Inhoud"
        name: "body"
        widget: "markdown"
