backend:
  name: github
  repo: JimGroen2160/spontaan-website
  branch: main
  base_url: https://plain-morning-bab6.jim-groen14.workers.dev
  auth_endpoint: auth

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pagina"
    label: "Pagina's"
    files:
      - file: "index.html"
        label: "Home"
        name: "home"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Intro tekst", name: "intro", widget: "text" }
