name: CI Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [main]

jobs:

  playwright:
    name: playwright
    runs-on: ubuntu-latest
    env:
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start local server
        run: |
          npx http-server . -p 5500 &
          npx wait-on http://localhost:5500

      - name: Run Playwright tests
        run: npx playwright test


  lighthouse:
    name: lighthouse
    needs: playwright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Start local server
        run: |
          npx http-server . -p 5500 &
          npx wait-on http://localhost:5500

      - name: Run Lighthouse CI
        run: |
          npx lhci autorun \
          --collect.url=http://localhost:5500 \
          --collect.numberOfRuns=1 \
          --assert.assertions.categories:performance=0.8 \
          --assert.assertions.categories:accessibility=0.9 \
          --assert.assertions.categories:seo=0.9 \
          --assert.assertions.categories:best-practices=0.9


  security:
    name: security
    needs: lighthouse
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run npm audit (blocking)
        run: npm audit --audit-level=high